# Default values for product-catalog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas:
  clientCount: 1
  serverCount: 1

builds:
  enable: true
  server:
    url: https://github.com/gnunn-gitops/product-catalog-server
    revision: master
    contextDir: /
  client:
    url: https://github.com/gnunn-gitops/product-catalog-client
    revision: master
    contextDir: /