apiVersion: v1
data:
  config.js: |
    window.ENV = {
        "API_URL":"http://server-{{ .Release.Namespace }}.{{ .Values.routes.subdomain }}"
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: product-catalog
  name: client