{{- if .Values.builds.enable }}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/gnunn-gitops/product-catalog-server'
  name: server
  labels:
    app: server
    app.kubernetes.io/name: server
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: server
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/part-of: product-catalog
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'server:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-11-el7'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/gnunn-gitops/product-catalog-server'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: product-catalog-server-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: product-catalog-server-github-webhook-secret
    - type: ImageChange
    - type: ConfigChange
  runPolicy: Serial
{{- end }}