{{- if .Values.builds.enable }}
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/gnunn-gitops/product-catalog-server'
  name: server
  labels:
    app: server
    app.kubernetes.io/name: server
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: server
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/part-of: product-catalog
spec:
  lookupPolicy:
    local: false
{{- end }}