# Note not currently working, pods constantly terminating and restarting
# Using DC for now but preserved here to come back to later
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  annotations:
    app.openshift.io/connects-to: database
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"server:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"server\")].image"}]'
  labels:
    app: server
    app.kubernetes.io/name: server
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: server
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/part-of: product-catalog
spec:
  selector:
    matchLabels:
      name: server
  replicas: {{ .Values.replicas.clientCount }}
  template:
    metadata:
      labels:
        name: server
        quarkus-prometheus: "true"
    spec:
      containers:
        - name: server
          env:
            - name: JAVA_OPTIONS
              value: >-
                -Dquarkus.kubernetes-config.enabled=true
                -Dquarkus.kubernetes-config.config-maps=server
            - name: CORS_ORIGIN
              value: http://client-{{ .Release.Namespace }}.{{ .Values.routes.suffix }}
          {{- if .Values.builds.enable }}
          image: image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/server:latest
          {{- else }}
          image: quay.io/gnunn/server:latest
          {{- end }}
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
            name: http
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
              httpGet:
                path: /health
                port: 8080
                scheme: HTTP
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File